
#this dictionary holds the data types for each field
dtypes_dict = {
  'source_id': 'u8',
  'parentid':'u8',
  'partid':'u2',
  'ra_true':'f8',
  'dec_true':'f8',
  'pmra_true':'f8',
  'pmdec_true':'f8',
  'pml_true':'f8',
  'pmb_true':'f8',
  'parallax_true':'f8',
  'dhel_true':'f8',
  'dmod_true':'f8',
  'radial_velocity_true': 'f8', 
  'l_true':'f8', 
  'b_true':'f8', 
  'px_true':'f8',
  'py_true':'f8',
  'pz_true':'f8', 
  'vx_true':'f8',
  'vy_true':'f8',
  'vz_true':'f8', 
  'phot_g_mean_mag_true': 'f4',
  'phot_bp_mean_mag_true': 'f4',
  'phot_rp_mean_mag_true': 'f4',
  'phot_g_mean_mag_int': 'f4',
  'phot_bp_mean_mag_int': 'f4',
  'phot_rp_mean_mag_int': 'f4',
  'mtip':'f4', 
  'mact':'f4',
  'mini':'f4',
  'age':'f4', 
  'logg':'f4',
  'feh':'f4',
  'alpha':'f4',
  'carbon':'f4',
  'helium':'f4',
  'nitrogen':'f4',
  'sulphur':'f4',
  'oxygen':'f4',
  'silicon':'f4',
  'calcium':'f4',
  'magnesium':'f4',
  'neon':'f4',
  'teff_val':'f4',
  'lum_val':'f4',
  'a_g_val':'f4', 
  'a_g_bp_val':'f4', 
  'a_g_rp_val':'f4', 
  'e_bp_min_rp_val':'f4',
  'ebv':'f4', 
  'lognh':'f4',
  'A0':'f4',
  'ra':'f8',
  'ra_error':'f8',
  'dec':'f8',
  'dec_error':'f8',
  'parallax':'f8',
  'parallax_error':'f8',
  'pmra':'f8',
  'pmra_error':'f8',
  'pmdec':'f8',
  'pmdec_error':'f8',
  'phot_g_mean_mag':  'f4',
  'phot_bp_mean_mag':  'f4',
  'phot_rp_mean_mag': 'f4',
  'phot_g_mean_mag_error': 'f4',
  'phot_bp_mean_mag_error':  'f4',
  'phot_rp_mean_mag_error':  'f4',
  'radial_velocity':'f8',
  'radial_velocity_error':'f8',
  'random_index':'u8', 
  'parallax_over_error':'f4',
  'l':'f8',
  'b':'f8',
  'bp_rp_int':'f4',
  'bp_g_int':'f4',
  'g_rp_int':'f4',
  'bp_rp_true':'f4',
  'bp_g_true':'f4',
  'g_rp_true':'f4',
  'bp_rp':'f4',
  'bp_g':'f4',
  'g_rp':'f4'
}

